export class Postulante {  
    id:number=0;
    nroDocumento:string='';
    nombres: string='';
    aPaterno:string='';
    aMaterno:string='';
    fechaNacimiento: string='';
    telefono:string='';
    direccion: string='';
    email:string='';    
    estadoCivil:string='';    
    discapacidad: string='';    
    sexo:string='';   
    nombreApoderado:string='';
    paternoApoderado:string='';
    maternoApoderado:string='';
    telefonoApoderado:string='';
    nacionalidad:string='';    
    anioEgreso:string='';
    promedioColegio:string='';
    regionColegio:string='';
    provinciaColegio:string='';
    distritoColegio:string='';
    colegio:string='';
    regionNacimiento:string='';
    provinciaNacimiento:string='';
    distritoNacimiento:string='';
    regionDomicilio:string='';
    provinciaDomicilio:string='';
    distritoDomicilio:string='';
    turno:string='';
    modalidad:string='';
    tipoDocumento:string=''; 
    transaccionPago:string='';
    foto:string=''; 
    ultimo:string='';
    fotoValidada: any;
    dniValidado:any;
}